batch_size: 4
classifier_step: 500
concept_head_path: /home/user_7734/training_myvlm/train_medical_clip_basic_llava/trained_concept_head/hyoidbone/seed_42
concept_identifier: hyoidbone
concept_name: hyoidbone
concept_type: OBJECT
data_root: /home/user_7734/training_myvlm/train_medical_clip_basic_llava/data/pos_hyoidbone
device: cuda
learning_rate: 0.0001
optimization_steps: 90
output_root: /home/user_7734/training_myvlm/train_medical_clip_basic_llava/output_concept_embedding_training
personalization_task: !!python/object/apply:myvlm.common.PersonalizationTask
- captioning
reg_lambda: 0.05
save_interval: 25
seed: 42
threshold: 0.5
torch_dtype: torch.bfloat16
val_interval: 10
vlm_type: !!python/object/apply:myvlm.common.VLMType
- llava
