batch_size: 4
classifier_step: 500
concept_head_path: /home/user_7734/omer/try_train_my_cat/concept_head_trained/my_cat/seed_42
concept_identifier: sks
concept_name: my_cat
concept_type: OBJECT
data_root: /home/user_7734/omer/try_train_my_cat
device: cuda
learning_rate: 1.0
optimization_steps: 100
output_root: /home/user_7734/omer/try_train_my_cat/embed_output
personalization_task: !!python/object/apply:myvlm.common.PersonalizationTask
- captioning
reg_lambda: 0.04
save_interval: 25
seed: 42
threshold: 0.5
torch_dtype: torch.bfloat16
val_interval: 25
vlm_type: !!python/object/apply:myvlm.common.VLMType
- blip-2
