batch_size: 3
classifier_step: 500
concept_head_path: /home/user_7734/training_myvlm/train_basic_clip_llava/trained_concept_head/my_cat/seed_42
concept_identifier: sks
concept_name: my_cat
concept_type: OBJECT
data_root: /home/user_7734/training_myvlm/train_basic_clip_llava/data/pos_cat
device: cuda
learning_rate: 1.0
optimization_steps: 100
output_root: /home/user_7734/training_myvlm/train_basic_clip_llava/output_concept_embedding_training
personalization_task: !!python/object/apply:myvlm.common.PersonalizationTask
- captioning
reg_lambda: 0.0075
save_interval: 25
seed: 42
threshold: 0.5
torch_dtype: torch.bfloat16
val_interval: 25
vlm_type: !!python/object/apply:myvlm.common.VLMType
- llava
